pipeline {
    agent any
       stage('Change Directory'){
            dir("/var/lib/jenkins/workspace/PipeLineAsCodeExample/java-maven-calculator-web-app-master"){
              sh "pwd"
                }   
	        }	 
	   stage('Build'){
          sh "mvn clean package"
           }
    }
